apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
    - name: app-container
      image: kriskhuslen/fortune:v1
      env:
        # Define the environment variable
        - name: INTERVAL #variable called internal in app # KEY NAME of Enviroment varible
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: fortune-config
              # Specify the key associated with the value
              key: sleep-time
