apiVersion: v1
kind: Service
metadata:
  name: simple-lb
spec:
  selector:
    app: lb
  ports:
    - protocol: TCP
      port: 80 #LOadbalancer port
      targetPort: 80 # Container pod
  type: LoadBalancer