apiVersion: v1
kind: Namespace
metadata:
  name: resources
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: super-app
  name: super-app
  namespace: resources
spec:
  replicas: 2
  selector:
    matchLabels:
      app: super-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: super-app
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            memory: "1Gi"
            cpu: "400m"
          limits:
            memory: "2Gi"
            cpu: "400"
