apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: application
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: httpd
  name: httpd
  namespace: application
spec:
  containers:
  - image: paketobuildpacks/httpd:0.7
    name: httpd
    command: ["/cnb/lifecycle/launcher"]
    args: ["httpd", "-DFOREGROUND"]
    ports:
    - containerPort: 80
      protocol: TCP