apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: akumo-pod
spec:
  containers:
  - name: akumo-container
    image: busybox 
    command: [ "/bin/sh"]
    args: ["-c", "sleep 5000"]
  restartPolicy: Always

